[2024-05-25 23:51:52,674: INFO: main: hello]
[2024-05-27 00:58:45,536: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-27 00:58:45,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 00:58:45,556: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 00:58:45,557: INFO: common: created directory at: artifacts]
[2024-05-27 00:58:45,559: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-27 00:58:45,559: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-27 00:58:56,241: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-27 00:59:00,856: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-27 21:02:18,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:02:18,184: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:02:18,190: INFO: common: created directory at: artifacts]
[2024-05-27 21:02:18,195: INFO: common: created directory at: artifacts/prepare_base_model/base_model.h5]
[2024-05-27 21:03:25,169: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:03:25,176: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:03:25,181: INFO: common: created directory at: artifacts]
[2024-05-27 21:03:25,184: INFO: common: created directory at: artifacts/prepare_base_model/base_model.h5]
[2024-05-27 21:06:45,424: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:06:45,432: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:06:45,436: INFO: common: created directory at: artifacts]
[2024-05-27 21:06:45,439: INFO: common: created directory at: artifacts/prepare_base_model/base_model.h5]
[2024-05-27 21:09:55,188: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:09:55,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:09:55,196: INFO: common: created directory at: artifacts]
[2024-05-27 21:09:55,198: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:11:55,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:11:55,242: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:11:55,244: INFO: common: created directory at: artifacts]
[2024-05-27 21:11:55,246: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:14:42,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:14:42,733: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:14:42,736: INFO: common: created directory at: artifacts]
[2024-05-27 21:14:42,738: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:14:51,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:14:51,484: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:14:51,487: INFO: common: created directory at: artifacts]
[2024-05-27 21:14:51,490: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:31:11,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:31:11,946: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:31:11,949: INFO: common: created directory at: artifacts]
[2024-05-27 21:31:11,951: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:33:10,189: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:33:10,197: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:33:10,200: INFO: common: created directory at: artifacts]
[2024-05-27 21:33:10,203: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:36:15,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:36:15,417: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:36:15,420: INFO: common: created directory at: artifacts]
[2024-05-27 21:36:15,424: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:47:44,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:47:44,520: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:47:44,523: INFO: common: created directory at: artifacts]
[2024-05-27 21:47:44,527: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 21:59:40,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 21:59:41,001: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 21:59:41,006: INFO: common: created directory at: artifacts]
[2024-05-27 21:59:41,012: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 22:01:59,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 22:01:59,764: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 22:01:59,769: INFO: common: created directory at: artifacts]
[2024-05-27 22:01:59,775: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 22:02:48,858: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-27 22:02:48,866: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-27 22:02:48,869: INFO: common: created directory at: artifacts]
[2024-05-27 22:02:48,872: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-27 22:03:03,530: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-27 22:03:04,074: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-29 18:29:35,208: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-29 18:29:35,261: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 18:29:35,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 18:29:35,266: INFO: common: created directory at: artifacts]
[2024-05-29 18:29:35,268: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-29 18:29:35,269: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-29 18:29:51,201: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-29 18:29:53,149: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-29 18:29:53,150: INFO: main: ******************]
[2024-05-29 18:29:53,150: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-29 18:29:53,158: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 18:29:53,166: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 18:29:53,167: INFO: common: created directory at: artifacts]
[2024-05-29 18:29:53,169: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-29 18:29:54,560: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-29 18:29:55,031: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-29 18:29:55,231: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-29 20:27:41,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:27:41,226: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:27:41,236: INFO: common: created directory at: artifacts]
[2024-05-29 20:30:18,001: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:30:18,008: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:30:18,011: INFO: common: created directory at: artifacts]
[2024-05-29 20:31:06,702: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:31:06,708: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:31:06,710: INFO: common: created directory at: artifacts]
[2024-05-29 20:31:38,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:31:38,738: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:31:38,742: INFO: common: created directory at: artifacts]
[2024-05-29 20:33:03,610: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:33:03,616: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:33:03,619: INFO: common: created directory at: artifacts]
[2024-05-29 20:34:15,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:34:15,606: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:34:15,610: INFO: common: created directory at: artifacts]
[2024-05-29 20:35:00,617: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:35:00,624: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:35:00,627: INFO: common: created directory at: artifacts]
[2024-05-29 20:36:48,203: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:36:48,210: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:36:48,213: INFO: common: created directory at: artifacts]
[2024-05-29 20:36:48,215: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:38:42,977: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:38:42,985: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:38:42,988: INFO: common: created directory at: artifacts]
[2024-05-29 20:38:42,990: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:41:50,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:41:50,043: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:41:50,046: INFO: common: created directory at: artifacts]
[2024-05-29 20:41:50,049: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:42:33,751: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:42:33,758: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:42:33,762: INFO: common: created directory at: artifacts]
[2024-05-29 20:42:33,768: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:44:58,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:44:58,248: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:44:58,250: INFO: common: created directory at: artifacts]
[2024-05-29 20:44:58,253: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:49:51,198: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:49:51,205: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:49:51,207: INFO: common: created directory at: artifacts]
[2024-05-29 20:49:51,210: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:51:27,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:51:27,466: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:51:27,469: INFO: common: created directory at: artifacts]
[2024-05-29 20:51:27,471: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:51:28,856: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-29 20:55:12,899: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 20:55:12,913: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 20:55:12,916: INFO: common: created directory at: artifacts]
[2024-05-29 20:55:12,921: INFO: common: created directory at: artifacts\training]
[2024-05-29 20:55:14,062: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-29 21:06:22,131: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 21:06:22,145: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 21:06:22,148: INFO: common: created directory at: artifacts]
[2024-05-29 21:06:22,151: INFO: common: created directory at: artifacts\training]
[2024-05-29 21:06:24,118: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-29 21:10:02,933: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-29 21:10:02,973: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-29 21:10:02,985: INFO: common: created directory at: artifacts]
[2024-05-29 21:10:02,999: INFO: common: created directory at: artifacts\training]
[2024-05-29 21:10:05,739: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-29 21:13:40,373: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 00:35:14,075: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 00:35:14,097: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 00:35:14,106: INFO: common: created directory at: artifacts]
[2024-05-30 00:35:14,109: INFO: common: created directory at: artifacts\training]
[2024-05-30 00:35:15,704: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-30 00:44:42,276: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:11:31,761: INFO: main: ******************]
[2024-05-30 01:11:31,763: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-30 01:11:31,766: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:11:31,770: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:11:31,771: INFO: common: created directory at: artifacts]
[2024-05-30 01:11:31,772: INFO: common: created directory at: artifacts\training]
[2024-05-30 01:11:33,378: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-30 01:11:55,426: ERROR: main: 'charmap' codec can't encode character '\u2501' in position 21: character maps to <undefined>]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 25, in <module>
    obj.main()
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 79, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2501' in position 21: character maps to <undefined>
[2024-05-30 01:28:45,970: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-30 01:28:45,974: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:28:45,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:28:45,979: INFO: common: created directory at: artifacts]
[2024-05-30 01:28:45,980: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-30 01:28:45,981: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-30 01:28:56,842: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-30 01:28:59,093: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-30 01:28:59,094: INFO: main: ******************]
[2024-05-30 01:28:59,094: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-30 01:28:59,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:28:59,104: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:28:59,105: INFO: common: created directory at: artifacts]
[2024-05-30 01:28:59,106: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-30 01:29:00,486: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:29:00,915: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:29:01,182: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-30 01:29:01,182: INFO: main: ******************]
[2024-05-30 01:29:01,183: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-30 01:29:01,192: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:29:01,198: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:29:01,200: INFO: common: created directory at: artifacts]
[2024-05-30 01:29:01,203: INFO: common: created directory at: artifacts\training]
[2024-05-30 01:29:01,690: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-30 01:29:20,042: ERROR: main: 'charmap' codec can't encode character '\u2501' in position 21: character maps to <undefined>]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 38, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 79, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2501' in position 21: character maps to <undefined>
[2024-05-30 01:43:19,845: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-30 01:43:19,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:43:19,851: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:43:19,853: INFO: common: created directory at: artifacts]
[2024-05-30 01:43:19,854: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-30 01:43:19,855: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-30 01:43:30,566: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-30 01:43:32,661: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-30 01:43:32,662: INFO: main: ******************]
[2024-05-30 01:43:32,662: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-30 01:43:32,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:43:32,674: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:43:32,675: INFO: common: created directory at: artifacts]
[2024-05-30 01:43:32,677: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-30 01:43:33,972: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:43:34,402: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:43:34,683: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-30 01:43:34,684: INFO: main: ******************]
[2024-05-30 01:43:34,684: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-30 01:43:34,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:43:34,699: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:43:34,700: INFO: common: created directory at: artifacts]
[2024-05-30 01:43:34,703: INFO: common: created directory at: artifacts\training]
[2024-05-30 01:43:35,361: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-30 01:43:52,746: ERROR: main: 'charmap' codec can't encode character '\u2501' in position 21: character maps to <undefined>]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 38, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 79, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u2501' in position 21: character maps to <undefined>
[2024-05-30 01:45:08,645: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-30 01:45:08,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:45:08,651: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:45:08,651: INFO: common: created directory at: artifacts]
[2024-05-30 01:45:08,652: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-30 01:45:08,653: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-30 01:45:19,693: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-30 01:45:21,558: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-30 01:45:21,559: INFO: main: ******************]
[2024-05-30 01:45:21,559: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-30 01:45:21,565: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:45:21,569: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:45:21,570: INFO: common: created directory at: artifacts]
[2024-05-30 01:45:21,576: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-30 01:45:22,445: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:45:22,707: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:45:22,866: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-30 01:45:22,867: INFO: main: ******************]
[2024-05-30 01:45:22,867: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-30 01:45:22,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-30 01:45:22,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-30 01:45:22,876: INFO: common: created directory at: artifacts]
[2024-05-30 01:45:22,877: INFO: common: created directory at: artifacts\training]
[2024-05-30 01:45:23,265: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-30 01:47:57,003: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-30 01:47:57,391: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-05-31 14:59:51,192: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 14:59:51,197: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 14:59:51,200: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 14:59:51,202: INFO: common: created directory at: artifacts]
[2024-05-31 14:59:51,203: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 14:59:51,204: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 15:00:02,206: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 15:00:04,339: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 15:00:04,340: INFO: main: ******************]
[2024-05-31 15:00:04,340: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 15:00:04,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:00:04,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:00:04,352: INFO: common: created directory at: artifacts]
[2024-05-31 15:00:04,354: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 15:00:05,731: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 15:00:06,263: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 15:00:06,758: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 15:00:06,758: INFO: main: ******************]
[2024-05-31 15:00:06,758: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 15:00:06,765: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:00:06,769: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:00:06,770: INFO: common: created directory at: artifacts]
[2024-05-31 15:00:06,773: INFO: common: created directory at: artifacts\training]
[2024-05-31 15:00:07,475: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 15:02:36,779: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 15:02:37,008: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-05-31 15:02:37,009: INFO: main: ******************]
[2024-05-31 15:02:37,009: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<<]
[2024-05-31 15:02:37,018: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:02:37,022: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:02:37,023: INFO: common: created directory at: artifacts]
[2024-05-31 15:02:37,574: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 15:03:19,004: INFO: common: json file saved at: scores.json]
[2024-05-31 15:03:19,006: INFO: common: json file saved at: scores.json]
[2024-05-31 15:03:54,845: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<<

x========x]
[2024-05-31 15:09:17,513: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 15:09:17,521: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:09:17,550: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:09:17,551: INFO: common: created directory at: artifacts]
[2024-05-31 15:09:17,552: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 15:09:17,553: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 15:09:28,302: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 15:09:30,448: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 15:09:30,449: INFO: main: ******************]
[2024-05-31 15:09:30,449: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 15:09:30,474: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:09:30,481: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:09:30,482: INFO: common: created directory at: artifacts]
[2024-05-31 15:09:30,483: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 15:09:31,612: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 15:09:32,104: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 15:09:32,540: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 15:09:32,541: INFO: main: ******************]
[2024-05-31 15:09:32,541: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 15:09:32,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:09:32,553: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:09:32,554: INFO: common: created directory at: artifacts]
[2024-05-31 15:09:32,555: INFO: common: created directory at: artifacts\training]
[2024-05-31 15:09:33,499: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 15:14:27,187: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 15:14:27,432: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-05-31 15:14:27,432: INFO: main: ******************]
[2024-05-31 15:14:27,432: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<<]
[2024-05-31 15:14:27,440: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 15:14:27,445: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 15:14:27,447: INFO: common: created directory at: artifacts]
[2024-05-31 15:14:28,876: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 15:15:10,451: INFO: common: json file saved at: scores.json]
[2024-05-31 15:15:10,454: INFO: common: json file saved at: scores.json]
[2024-05-31 15:15:48,055: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<<

x========x]
[2024-05-31 22:03:32,406: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 22:03:32,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:03:32,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:03:32,437: INFO: common: created directory at: artifacts]
[2024-05-31 22:03:32,438: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 22:03:32,438: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 22:03:50,770: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 22:03:52,556: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 22:03:52,557: INFO: main: ******************]
[2024-05-31 22:03:52,557: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 22:03:52,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:03:52,570: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:03:52,571: INFO: common: created directory at: artifacts]
[2024-05-31 22:03:52,578: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 22:03:54,311: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:05:38,756: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 22:05:38,760: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:05:38,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:05:38,773: INFO: common: created directory at: artifacts]
[2024-05-31 22:05:38,774: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 22:05:38,775: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 22:06:05,056: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 22:06:06,803: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 22:06:06,804: INFO: main: ******************]
[2024-05-31 22:06:06,805: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 22:06:06,811: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:06:06,817: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:06:06,818: INFO: common: created directory at: artifacts]
[2024-05-31 22:06:06,819: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 22:06:07,952: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:06:08,257: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:06:08,617: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 22:06:08,618: INFO: main: ******************]
[2024-05-31 22:06:08,619: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 22:06:08,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:06:08,634: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:06:08,636: INFO: common: created directory at: artifacts]
[2024-05-31 22:06:08,641: INFO: common: created directory at: artifacts\training]
[2024-05-31 22:06:09,074: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:14:56,621: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:14:57,045: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-05-31 22:14:57,045: INFO: main: ******************]
[2024-05-31 22:14:57,045: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<<]
[2024-05-31 22:14:57,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:14:57,077: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:14:57,080: INFO: common: created directory at: artifacts]
[2024-05-31 22:14:58,753: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:15:47,716: INFO: common: json file saved at: scores.json]
[2024-05-31 22:15:47,718: INFO: common: json file saved at: scores.json]
[2024-05-31 22:15:57,516: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<<

x========x]
[2024-05-31 22:22:08,472: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 22:22:08,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:22:08,482: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:22:08,483: INFO: common: created directory at: artifacts]
[2024-05-31 22:22:08,484: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 22:22:08,487: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 22:22:27,218: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 22:22:28,920: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 22:22:28,920: INFO: main: ******************]
[2024-05-31 22:22:28,920: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 22:22:28,924: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:22:28,928: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:22:28,929: INFO: common: created directory at: artifacts]
[2024-05-31 22:22:28,929: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 22:22:30,313: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:22:30,680: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:22:31,108: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 22:22:31,108: INFO: main: ******************]
[2024-05-31 22:22:31,108: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 22:22:31,117: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:22:31,122: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:22:31,123: INFO: common: created directory at: artifacts]
[2024-05-31 22:22:31,124: INFO: common: created directory at: artifacts\training]
[2024-05-31 22:22:31,892: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:25:40,727: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:25:41,056: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-05-31 22:25:41,057: INFO: main: ******************]
[2024-05-31 22:25:41,058: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<<]
[2024-05-31 22:25:41,066: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:25:41,077: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:25:41,080: INFO: common: created directory at: artifacts]
[2024-05-31 22:25:41,728: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:26:35,144: INFO: common: json file saved at: scores.json]
[2024-05-31 22:26:35,147: INFO: common: json file saved at: scores.json]
[2024-05-31 22:26:43,282: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<<

x========x]
[2024-05-31 22:43:05,201: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 22:43:05,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:43:05,211: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:43:05,213: INFO: common: created directory at: artifacts]
[2024-05-31 22:43:05,214: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 22:43:05,215: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 22:43:21,073: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 22:43:28,302: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 22:43:28,303: INFO: main: ******************]
[2024-05-31 22:43:28,303: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 22:43:28,313: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:43:28,371: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:43:28,372: INFO: common: created directory at: artifacts]
[2024-05-31 22:43:28,381: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 22:43:30,833: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:43:31,799: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:43:32,320: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 22:43:32,320: INFO: main: ******************]
[2024-05-31 22:43:32,321: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 22:43:32,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:43:32,337: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:43:32,338: INFO: common: created directory at: artifacts]
[2024-05-31 22:43:32,339: INFO: common: created directory at: artifacts\training]
[2024-05-31 22:43:33,372: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:46:29,019: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:46:29,361: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-05-31 22:46:29,361: INFO: main: ******************]
[2024-05-31 22:46:29,361: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<<]
[2024-05-31 22:46:29,381: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:46:29,388: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:46:29,392: INFO: common: created directory at: artifacts]
[2024-05-31 22:46:31,427: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:47:12,757: INFO: common: json file saved at: scores.json]
[2024-05-31 22:47:12,759: INFO: common: json file saved at: scores.json]
[2024-05-31 22:47:45,298: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<<

x========x]
[2024-05-31 22:59:35,402: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 22:59:35,407: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:59:35,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:59:35,424: INFO: common: created directory at: artifacts]
[2024-05-31 22:59:35,425: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 22:59:35,426: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 22:59:52,735: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 22:59:54,554: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 22:59:54,554: INFO: main: ******************]
[2024-05-31 22:59:54,555: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 22:59:54,566: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:59:54,576: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:59:54,578: INFO: common: created directory at: artifacts]
[2024-05-31 22:59:54,579: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 22:59:55,808: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:59:56,151: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 22:59:56,443: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 22:59:56,444: INFO: main: ******************]
[2024-05-31 22:59:56,444: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 22:59:56,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 22:59:56,452: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 22:59:56,454: INFO: common: created directory at: artifacts]
[2024-05-31 22:59:56,455: INFO: common: created directory at: artifacts\training]
[2024-05-31 22:59:56,870: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 22:59:59,414: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 79, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-05-31 23:37:09,310: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 23:37:09,315: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 23:37:09,318: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 23:37:09,319: INFO: common: created directory at: artifacts]
[2024-05-31 23:37:09,320: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 23:37:09,321: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 23:37:20,146: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 23:37:21,948: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 23:37:21,948: INFO: main: ******************]
[2024-05-31 23:37:21,949: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 23:37:21,955: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 23:37:21,959: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 23:37:21,960: INFO: common: created directory at: artifacts]
[2024-05-31 23:37:21,961: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 23:37:23,176: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 23:37:23,395: ERROR: main: module 'keras.api.optimizers' has no attribute 'adam']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 36, in <module>
    prepare_base_model.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.update_base_model()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\prepare_base_model.py", line 44, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\prepare_base_model.py", line 36, in _prepare_full_model
    full_model.compile(optimizer=tf.keras.optimizers.adam(learning_rate=learning_rate),
                                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'keras.api.optimizers' has no attribute 'adam'. Did you mean: 'Adam'?
[2024-05-31 23:39:52,049: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-05-31 23:39:52,054: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 23:39:52,057: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 23:39:52,058: INFO: common: created directory at: artifacts]
[2024-05-31 23:39:52,059: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-31 23:39:52,060: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-05-31 23:40:02,986: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-05-31 23:40:04,576: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-05-31 23:40:04,576: INFO: main: ******************]
[2024-05-31 23:40:04,577: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-05-31 23:40:04,582: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 23:40:04,586: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 23:40:04,587: INFO: common: created directory at: artifacts]
[2024-05-31 23:40:04,588: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-31 23:40:05,984: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 23:40:06,489: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-05-31 23:40:06,673: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-05-31 23:40:06,674: INFO: main: ******************]
[2024-05-31 23:40:06,674: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-05-31 23:40:06,679: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-31 23:40:06,683: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-31 23:40:06,684: INFO: common: created directory at: artifacts]
[2024-05-31 23:40:06,687: INFO: common: created directory at: artifacts\training]
[2024-05-31 23:40:07,615: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-31 23:40:07,681: ERROR: main: Training.train() missing 1 required positional argument: 'learning_rate']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
TypeError: Training.train() missing 1 required positional argument: 'learning_rate'
[2024-06-01 00:05:19,627: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:05:19,631: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:05:19,632: INFO: common: created directory at: artifacts]
[2024-06-01 00:05:19,633: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:05:20,519: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 00:13:56,358: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:13:56,360: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:13:56,361: INFO: common: created directory at: artifacts]
[2024-06-01 00:13:56,362: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:25:50,042: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:25:50,047: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:25:50,048: INFO: common: created directory at: artifacts]
[2024-06-01 00:25:50,049: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:41:16,230: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:41:16,233: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:41:16,234: INFO: common: created directory at: artifacts]
[2024-06-01 00:41:16,235: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 00:41:16,236: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:41:17,190: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:41:17,797: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:41:18,724: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 00:41:21,021: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 00:41:21,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:41:21,027: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:41:21,028: INFO: common: created directory at: artifacts]
[2024-06-01 00:41:21,029: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 00:41:21,030: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 00:41:35,031: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 00:41:36,824: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 00:41:36,825: INFO: main: ******************]
[2024-06-01 00:41:36,825: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 00:41:36,833: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:41:36,841: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:41:36,842: INFO: common: created directory at: artifacts]
[2024-06-01 00:41:36,843: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 00:41:37,866: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:41:38,740: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:41:39,008: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:41:39,283: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 00:41:39,283: INFO: main: ******************]
[2024-06-01 00:41:39,284: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 00:41:39,291: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:41:39,300: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:41:39,301: INFO: common: created directory at: artifacts]
[2024-06-01 00:41:39,302: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:41:39,929: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 00:41:42,589: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense_1/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 81, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense_1/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 00:45:29,800: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 00:45:29,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:45:29,807: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:45:29,808: INFO: common: created directory at: artifacts]
[2024-06-01 00:45:29,809: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 00:45:29,810: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 00:45:40,776: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 00:45:42,491: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 00:45:42,492: INFO: main: ******************]
[2024-06-01 00:45:42,492: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 00:45:42,509: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:45:42,514: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:45:42,515: INFO: common: created directory at: artifacts]
[2024-06-01 00:45:42,518: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 00:45:43,586: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:45:44,253: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:45:44,521: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:45:44,975: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 00:45:44,976: INFO: main: ******************]
[2024-06-01 00:45:44,976: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 00:45:44,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:45:44,996: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:45:44,999: INFO: common: created directory at: artifacts]
[2024-06-01 00:45:45,001: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:45:45,684: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 00:45:47,836: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 00:54:34,458: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 00:54:34,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:54:34,465: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:54:34,466: INFO: common: created directory at: artifacts]
[2024-06-01 00:54:34,467: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 00:54:34,468: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 00:54:45,467: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 00:54:46,891: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 00:54:46,891: INFO: main: ******************]
[2024-06-01 00:54:46,892: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 00:54:46,902: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:54:46,922: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:54:46,940: INFO: common: created directory at: artifacts]
[2024-06-01 00:54:46,953: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 00:54:48,068: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:54:48,788: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:54:49,051: ERROR: main: 'PrepareBaseModel' object has no attribute 'full_model']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 36, in <module>
    prepare_base_model.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.update_base_model()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\prepare_base_model.py", line 53, in update_base_model
    self.save_model(path=self.config.updated_base_model_path, model=self.full_model)
                                                                    ^^^^^^^^^^^^^^^
AttributeError: 'PrepareBaseModel' object has no attribute 'full_model'
[2024-06-01 00:57:16,132: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 00:57:16,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:57:16,139: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:57:16,139: INFO: common: created directory at: artifacts]
[2024-06-01 00:57:16,140: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 00:57:16,141: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 00:57:27,092: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 00:57:28,346: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 00:57:28,346: INFO: main: ******************]
[2024-06-01 00:57:28,347: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 00:57:28,352: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:57:28,356: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:57:28,357: INFO: common: created directory at: artifacts]
[2024-06-01 00:57:28,358: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 00:57:29,800: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:57:30,687: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:57:30,925: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 00:57:31,204: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 00:57:31,206: INFO: main: ******************]
[2024-06-01 00:57:31,206: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 00:57:31,226: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 00:57:31,232: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 00:57:31,233: INFO: common: created directory at: artifacts]
[2024-06-01 00:57:31,234: INFO: common: created directory at: artifacts\training]
[2024-06-01 00:57:31,968: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 00:57:34,097: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 01:09:54,882: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:09:54,887: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:09:54,889: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:09:54,891: INFO: common: created directory at: artifacts]
[2024-06-01 01:09:54,891: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:09:54,892: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:10:05,473: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:10:06,985: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:10:06,986: INFO: main: ******************]
[2024-06-01 01:10:06,986: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:10:06,992: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:10:06,995: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:10:06,996: INFO: common: created directory at: artifacts]
[2024-06-01 01:10:06,998: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:10:08,185: ERROR: main: 'PrepareBaseModelConfig' object has no attribute 'base_model_path']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 36, in <module>
    prepare_base_model.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model.get_base_model()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\prepare_base_model.py", line 21, in get_base_model
    self.save_model(path=self.config.base_model_path, model=self.model)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'base_model_path'. Did you mean: 'base_mode_path'?
[2024-06-01 01:20:22,499: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:20:22,504: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:20:22,506: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:20:22,507: INFO: common: created directory at: artifacts]
[2024-06-01 01:20:22,508: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:20:22,509: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:20:34,785: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:20:43,880: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:20:43,880: INFO: main: ******************]
[2024-06-01 01:20:43,881: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:20:43,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:20:43,895: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:20:43,897: INFO: common: created directory at: artifacts]
[2024-06-01 01:20:43,899: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:20:50,615: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:20:51,763: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:20:59,046: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:20:59,975: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 01:20:59,975: INFO: main: ******************]
[2024-06-01 01:20:59,975: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 01:20:59,979: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:20:59,983: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:20:59,984: INFO: common: created directory at: artifacts]
[2024-06-01 01:20:59,986: INFO: common: created directory at: artifacts\training]
[2024-06-01 01:21:00,508: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 01:21:02,769: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 73, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 01:28:11,328: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:28:11,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:28:11,337: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:28:11,337: INFO: common: created directory at: artifacts]
[2024-06-01 01:28:11,338: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:28:11,339: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:28:22,432: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:28:23,922: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:28:23,923: INFO: main: ******************]
[2024-06-01 01:28:23,923: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:28:23,929: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:28:23,933: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:28:23,934: INFO: common: created directory at: artifacts]
[2024-06-01 01:28:23,935: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:28:25,140: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:28:25,886: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:28:26,186: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:28:26,681: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 01:28:26,682: INFO: main: ******************]
[2024-06-01 01:28:26,682: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 01:28:26,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:28:26,699: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:28:26,700: INFO: common: created directory at: artifacts]
[2024-06-01 01:28:26,701: INFO: common: created directory at: artifacts\training]
[2024-06-01 01:28:27,315: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 01:28:29,097: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 01:28:31,661: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 01:29:18,565: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:29:18,569: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:29:18,572: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:29:18,573: INFO: common: created directory at: artifacts]
[2024-06-01 01:29:18,573: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:29:18,574: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:29:30,036: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:29:31,540: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:29:31,540: INFO: main: ******************]
[2024-06-01 01:29:31,541: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:29:31,546: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:29:31,551: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:29:31,551: INFO: common: created directory at: artifacts]
[2024-06-01 01:29:31,552: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:29:32,794: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:29:34,523: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:29:35,693: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:29:40,782: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 01:29:40,782: INFO: main: ******************]
[2024-06-01 01:29:40,782: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 01:29:40,789: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:29:40,793: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:29:40,794: INFO: common: created directory at: artifacts]
[2024-06-01 01:29:40,794: INFO: common: created directory at: artifacts\training]
[2024-06-01 01:29:41,870: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 01:29:43,534: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 01:29:45,900: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 01:38:33,532: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:38:33,537: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:38:33,540: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:38:33,540: INFO: common: created directory at: artifacts]
[2024-06-01 01:38:33,541: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:38:33,542: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:38:44,237: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:38:45,879: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:38:45,880: INFO: main: ******************]
[2024-06-01 01:38:45,880: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:38:45,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:38:45,913: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:38:45,914: INFO: common: created directory at: artifacts]
[2024-06-01 01:38:45,916: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:38:47,239: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:38:48,259: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:38:48,681: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:38:49,050: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 01:38:49,051: INFO: main: ******************]
[2024-06-01 01:38:49,051: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 01:38:49,057: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:38:49,063: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:38:49,064: INFO: common: created directory at: artifacts]
[2024-06-01 01:38:49,065: INFO: common: created directory at: artifacts\training]
[2024-06-01 01:38:49,511: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 01:38:51,145: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 01:38:53,442: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 01:44:30,625: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:44:30,630: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:44:30,633: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:44:30,633: INFO: common: created directory at: artifacts]
[2024-06-01 01:44:30,634: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:44:30,634: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:44:45,196: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:44:48,147: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:44:48,147: INFO: main: ******************]
[2024-06-01 01:44:48,148: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:44:48,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:44:48,159: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:44:48,161: INFO: common: created directory at: artifacts]
[2024-06-01 01:44:48,161: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:44:55,652: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:44:58,037: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:45:00,620: ERROR: main: PrepareBaseModel._prepare_full_model() missing 1 required positional argument: 'learning_rate']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 36, in <module>
    prepare_base_model.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.update_base_model()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\prepare_base_model.py", line 46, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PrepareBaseModel._prepare_full_model() missing 1 required positional argument: 'learning_rate'
[2024-06-01 01:48:13,594: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:48:13,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:48:13,601: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:48:13,602: INFO: common: created directory at: artifacts]
[2024-06-01 01:48:13,603: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:48:13,604: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:48:24,758: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:48:26,256: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:48:26,256: INFO: main: ******************]
[2024-06-01 01:48:26,256: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:48:26,262: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:48:26,266: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:48:26,267: INFO: common: created directory at: artifacts]
[2024-06-01 01:48:26,268: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:48:27,409: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:48:28,195: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:48:28,399: ERROR: main: PrepareBaseModel._prepare_full_model() missing 1 required positional argument: 'learning_rate']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 36, in <module>
    prepare_base_model.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.update_base_model()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\prepare_base_model.py", line 46, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PrepareBaseModel._prepare_full_model() missing 1 required positional argument: 'learning_rate'
[2024-06-01 01:51:40,869: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:51:40,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:51:40,876: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:51:40,877: INFO: common: created directory at: artifacts]
[2024-06-01 01:51:40,877: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:51:40,878: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:51:51,651: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:51:53,249: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:51:53,249: INFO: main: ******************]
[2024-06-01 01:51:53,250: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:51:53,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:51:53,260: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:51:53,262: INFO: common: created directory at: artifacts]
[2024-06-01 01:51:53,262: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:51:54,546: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:51:55,266: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:51:55,436: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:51:55,608: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 01:51:55,609: INFO: main: ******************]
[2024-06-01 01:51:55,609: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 01:51:55,615: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:51:55,619: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:51:55,620: INFO: common: created directory at: artifacts]
[2024-06-01 01:51:55,622: INFO: common: created directory at: artifacts\training]
[2024-06-01 01:51:56,314: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 01:51:57,920: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 01:52:00,313: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 01:56:02,779: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 01:56:02,783: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:56:02,786: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:56:02,786: INFO: common: created directory at: artifacts]
[2024-06-01 01:56:02,787: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 01:56:02,787: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 01:56:13,611: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 01:56:17,595: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 01:56:17,595: INFO: main: ******************]
[2024-06-01 01:56:17,596: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 01:56:17,605: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:56:17,610: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:56:17,611: INFO: common: created directory at: artifacts]
[2024-06-01 01:56:17,612: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 01:56:19,627: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:56:20,741: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:56:21,164: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 01:56:21,521: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 01:56:21,521: INFO: main: ******************]
[2024-06-01 01:56:21,522: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 01:56:21,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 01:56:21,529: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 01:56:21,530: INFO: common: created directory at: artifacts]
[2024-06-01 01:56:21,531: INFO: common: created directory at: artifacts\training]
[2024-06-01 01:56:22,041: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 01:56:23,470: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 01:56:26,355: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 02:05:21,743: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 02:05:21,748: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:05:21,752: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:05:21,753: INFO: common: created directory at: artifacts]
[2024-06-01 02:05:21,754: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 02:05:21,755: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 02:05:32,712: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 02:05:34,291: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 02:05:34,292: INFO: main: ******************]
[2024-06-01 02:05:34,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 02:05:34,298: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:05:34,303: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:05:34,304: INFO: common: created directory at: artifacts]
[2024-06-01 02:05:34,305: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 02:05:35,832: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:05:37,341: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:05:38,351: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:05:38,773: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 02:05:38,774: INFO: main: ******************]
[2024-06-01 02:05:38,774: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 02:05:38,779: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:05:38,788: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:05:38,791: INFO: common: created directory at: artifacts]
[2024-06-01 02:05:38,792: INFO: common: created directory at: artifacts\training]
[2024-06-01 02:05:39,539: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:05:41,639: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 02:05:43,955: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 74, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 02:10:16,032: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 02:10:16,036: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:10:16,039: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:10:16,040: INFO: common: created directory at: artifacts]
[2024-06-01 02:10:16,040: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 02:10:16,041: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 02:10:26,435: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 02:10:27,700: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 02:10:27,700: INFO: main: ******************]
[2024-06-01 02:10:27,701: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 02:10:27,706: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:10:27,711: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:10:27,712: INFO: common: created directory at: artifacts]
[2024-06-01 02:10:27,712: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 02:10:28,908: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:10:29,654: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:10:29,899: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:10:30,157: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 02:10:30,157: INFO: main: ******************]
[2024-06-01 02:10:30,158: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 02:10:30,163: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:10:30,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:10:30,169: INFO: common: created directory at: artifacts]
[2024-06-01 02:10:30,170: INFO: common: created directory at: artifacts\training]
[2024-06-01 02:10:30,907: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:10:34,124: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 02:10:35,064: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:10:39,395: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 81, in train
    self.model.fit(
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 02:21:45,656: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 02:21:45,660: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:21:45,663: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:21:45,664: INFO: common: created directory at: artifacts]
[2024-06-01 02:21:45,664: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 02:21:45,665: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 02:22:00,667: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 02:22:02,305: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 02:22:02,305: INFO: main: ******************]
[2024-06-01 02:22:02,306: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 02:22:02,311: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:22:02,315: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:22:02,316: INFO: common: created directory at: artifacts]
[2024-06-01 02:22:02,317: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 02:22:03,535: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:22:04,372: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:22:05,044: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:22:05,312: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 02:22:05,312: INFO: main: ******************]
[2024-06-01 02:22:05,312: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 02:22:05,317: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:22:05,319: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:22:05,320: INFO: common: created directory at: artifacts]
[2024-06-01 02:22:05,320: INFO: common: created directory at: artifacts\training]
[2024-06-01 02:22:05,705: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:22:07,113: WARNING: module_wrapper: From C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.
]
[2024-06-01 02:22:07,704: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:22:09,856: ERROR: main: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 115, in train
    raise e  # Re-raise the exception to halt execution and see the full traceback
    ^^^^^^^
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_training.py", line 96, in train
    history = self.model.fit(
              ^^^^^^^^^^^^^^^
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\AJAY KUMAR\anaconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 228, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <KerasVariable shape=(25088, 2), dtype=float32, path=dense/kernel>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2024-06-01 02:24:32,750: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 02:24:32,754: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:24:32,757: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:24:32,757: INFO: common: created directory at: artifacts]
[2024-06-01 02:24:32,758: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 02:24:32,758: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 02:24:44,845: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 02:24:46,118: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 02:24:46,118: INFO: main: ******************]
[2024-06-01 02:24:46,118: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 02:24:46,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:24:46,124: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:24:46,125: INFO: common: created directory at: artifacts]
[2024-06-01 02:24:46,126: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 02:24:47,169: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:24:47,959: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:24:48,271: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:24:48,599: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 02:24:48,600: INFO: main: ******************]
[2024-06-01 02:24:48,600: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 02:24:48,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:24:48,612: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:24:48,613: INFO: common: created directory at: artifacts]
[2024-06-01 02:24:48,614: INFO: common: created directory at: artifacts\training]
[2024-06-01 02:24:48,615: ERROR: main: 'Training' object has no attribute 'get_base_model']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 15, in main
    training.get_base_model()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Training' object has no attribute 'get_base_model'
[2024-06-01 02:28:27,706: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 02:28:27,720: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:28:27,736: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:28:27,737: INFO: common: created directory at: artifacts]
[2024-06-01 02:28:27,738: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 02:28:27,739: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 02:28:42,868: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 02:28:45,895: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 02:28:45,895: INFO: main: ******************]
[2024-06-01 02:28:45,896: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 02:28:45,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:28:45,906: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:28:45,907: INFO: common: created directory at: artifacts]
[2024-06-01 02:28:45,908: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 02:28:47,863: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:28:49,653: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:28:50,236: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:28:50,510: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 02:28:50,510: INFO: main: ******************]
[2024-06-01 02:28:50,510: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 02:28:50,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:28:50,530: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:28:50,532: INFO: common: created directory at: artifacts]
[2024-06-01 02:28:50,533: INFO: common: created directory at: artifacts\training]
[2024-06-01 02:28:50,534: ERROR: main: 'Training' object has no attribute 'get_base_model']
Traceback (most recent call last):
  File "C:\Users\AJAY KUMAR\Desktop\kidney_project\Kidney-Disease-Classification-Deep-Learning-Project\main.py", line 49, in <module>
    model_trainer.main()
  File "c:\users\ajay kumar\desktop\kidney_project\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_03_model_training.py", line 15, in main
    training.get_base_model()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Training' object has no attribute 'get_base_model'
[2024-06-01 02:31:21,463: INFO: main: >>>>>> stage  Data Ingestion stage started <<<<<<<]
[2024-06-01 02:31:21,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:31:21,470: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:31:21,471: INFO: common: created directory at: artifacts]
[2024-06-01 02:31:21,471: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-01 02:31:21,472: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into the artifacts/data_ingestion/data.zip]
[2024-06-01 02:31:32,005: INFO: data_ingestion: Download data from https://drive.google.com/file/d/1aOA1AS9SuElVxdJHE48GFLCNRsDXBwpY/view?usp=drive_link into file artifacts/data_ingestion/data.zip]
[2024-06-01 02:31:33,260: INFO: main: >>>>>> stage  Data Ingestion stage completed <<<<<<<

x========x]
[2024-06-01 02:31:33,260: INFO: main: ******************]
[2024-06-01 02:31:33,261: INFO: main: >>>>>> stage Prepare base model started <<<<<<<]
[2024-06-01 02:31:33,267: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:31:33,272: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:31:33,273: INFO: common: created directory at: artifacts]
[2024-06-01 02:31:33,274: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-01 02:31:34,431: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:31:35,275: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:31:35,606: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:31:35,990: INFO: main: >>>>>> stage Prepare base model completed <<<<<<<

x========x]
[2024-06-01 02:31:35,990: INFO: main: ******************]
[2024-06-01 02:31:35,990: INFO: main: >>>>>> stage model training started <<<<<<<]
[2024-06-01 02:31:35,994: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:31:35,997: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:31:35,998: INFO: common: created directory at: artifacts]
[2024-06-01 02:31:35,998: INFO: common: created directory at: artifacts\training]
[2024-06-01 02:31:36,609: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:34:04,678: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-01 02:34:04,896: INFO: main: >>>>>> stage model training completed <<<<<<<

x========x]
[2024-06-01 02:34:04,896: INFO: main: ******************]
[2024-06-01 02:34:04,896: INFO: main: >>>>>> stage Evaluation Stage started <<<<<<<]
[2024-06-01 02:34:04,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-01 02:34:04,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-01 02:34:04,905: INFO: common: created directory at: artifacts]
[2024-06-01 02:34:05,274: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-01 02:34:47,644: INFO: common: json file saved at: scores.json]
[2024-06-01 02:34:47,645: INFO: common: json file saved at: scores.json]
[2024-06-01 02:35:46,798: INFO: main: >>>>>> stage Evaluation Stage completed <<<<<<<

x========x]
